name: Build APK

on:
  push:
    paths-ignore: [ '**.md' ]
  pull_request:
    paths-ignore: [ '**.md' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assembleRelease --stacktrace --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: XSpoofSignatures
          if-no-files-found: error
          path: |
            app/build/outputs/apk/release/app-release.apk
