name: Publish Release

concurrency:
  group: "release"
  cancel-in-progress: true

on:
  push:
    tags: [ "*.*.*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Build
        env:
          KEYSTORE_FILE: ./release.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo '${{ secrets.KEYSTORE }}' | base64 -d > ./release.jks
          chmod +x ./gradlew
          RELEASE=true ./gradlew :app:assembleRelease --stacktrace --no-daemon
          mv -T ./app/build/outputs/apk/release/app-release.apk dev.rushii.xspoofsignatures-${{ github.ref_name }}.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: XSpoofSignatures
          if-no-files-found: error
          path: |
            dev.rushii.xspoofsignatures-${{ github.ref_name }}.apk

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: dev.rushii.xspoofsignatures-${{ github.ref_name }}.apk
